ssi:
  run: false
  volume_size: 256
  scales_range: [1, 10]
  scales_numbers: [1, 2, 3]

vsi:
  run: false
  volume_sizes: [32, 64, 128]

cni:
  run: false
  volume_sizes: [32, 64, 128]
  chunk_numbers: [2, 4, 8]

pac:
  run: false
  input_file: test.nii
