setup:
  name: benchmark
  input_dir: data/test
  output_dir: outputs/test
  log_dir: logs
  log_file: benchmark
  debug_mode: true
  display_mode: true
  save_mode: true

experiment:
  load:
    normalize: true
    crop: true
    target_shape: [64, 64, 64]
    input_file: null
    output_file: null

  methods:
    derivator: default
    enhancer: frangi
    segmenter: thresholding

  hessian:
    mode: reflect
    cval: 0.0

  processing:
    normalize: true
    parallelize: false
    chunk_size: [32, 32, 32]
    overlap_size: 8

  enhancement:
    alpha: 0.5
    beta: 0.5
    gamma: 15
    # scales: [1, 2, 10]
    scales: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15]
    scales_number: null
    scales_range: null
    black_ridges: true
    skimage: false

  segmentation:
    threshold: null

runner:
  params_grid:
    alpha: [0.1, 0.5]
    beta: [0.1, 0.5]
    # gamma: [null]
    gamma: [null, 0.1, 1.0, 10]
  methods: [
      "default",
      "gaussian",
      "farid",
      # "cubic",
      # "trigonometric",
      # "catmull",
      # "bspline",
      # "bezier",
    ]
  raw_file: raw.png
  gt_file: gt.png
