general:
  project_name: "vascular_enhancement"
  root_dir: "."
  input_dir: "./data"
  output_dir: "./results"
  log_dir: "./logs"
  use_multithreading: true
  num_threads: 4
  d_type: float32

data:
  input_dir: "./data/raw"
  allowed_formats: [".tif", ".nii", ".png", ".jpg"]
  recursive_scan: true
  save_as_nii: true

chunker:
  chunk_size: [100, 100, 100]
  crop_size: [null, null, null]

logger:
  debug_mode: true

differentiation:
  method: "farid" # farid, hast, skimage, custom

enhancement:
  method: "frangi" # frangi
  scale_range: [1, 10]
  scale_step: 2
  # scales: [2, 4, 6, 8, 10]
  alpha: 0.5
  beta: 0.5
  gamma: null

benchmark:
  compute_metrics: true
  metrics: ["ssim", "psnr", "dice"]
  export_plots: true
  visual_output: true
